"""upadte associate tabel

Revision ID: 0c4d18155a27
Revises: 64e6c0903c9a
Create Date: 2021-11-16 09:52:25.808519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4d18155a27'
down_revision = '64e6c0903c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association', 'tags_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('association', 'posts_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association', 'posts_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('association', 'tags_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
