"""many to many relation between tag and post

Revision ID: 64e6c0903c9a
Revises: 15620193ba39
Create Date: 2021-11-15 18:03:22.516989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e6c0903c9a'
down_revision = '15620193ba39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('posts_id', sa.Integer(), nullable=False))
    op.drop_constraint('association_tags_id_fkey', 'association', type_='foreignkey')
    op.drop_constraint('association_posts.id_fkey', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'tags', ['tags_id'], ['id'])
    op.create_foreign_key(None, 'association', 'posts', ['posts_id'], ['id'])
    op.drop_column('association', 'posts.id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('posts.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key('association_posts.id_fkey', 'association', 'tags', ['posts.id'], ['id'])
    op.create_foreign_key('association_tags_id_fkey', 'association', 'posts', ['tags_id'], ['id'])
    op.drop_column('association', 'posts_id')
    # ### end Alembic commands ###
